/*
 * SnookrGUIAboutBox.java
 */
package snookrgui;

import java.awt.Component;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;

public class SnookrGUIPreferences extends javax.swing.JDialog {

    public SnookrGUIPreferences(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(cancelButton);
    }

    @Action
    public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        baseDirTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pickDirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(snookrgui.SnookrGUIApp.class).getContext().getResourceMap(SnookrGUIPreferences.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(snookrgui.SnookrGUIApp.class).getContext().getActionMap(SnookrGUIPreferences.class, this);
        cancelButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        saveBtn.setAction(actionMap.get("closeAboutBox")); // NOI18N
        saveBtn.setText(resourceMap.getString("saveBtn.text")); // NOI18N
        saveBtn.setName("saveBtn"); // NOI18N

        baseDirTextField.setText(resourceMap.getString("baseDirTextField.text")); // NOI18N
        baseDirTextField.setName("baseDirTextField"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        pickDirBtn.setAction(actionMap.get("pickDirectory")); // NOI18N
        pickDirBtn.setText(resourceMap.getString("pickDirBtn.text")); // NOI18N
        pickDirBtn.setName("pickDirBtn"); // NOI18N
        pickDirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pickDirBtnMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .add(saveBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cancelButton)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(baseDirTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 307, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pickDirBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(baseDirTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(pickDirBtn))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 112, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(saveBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pickDirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickDirBtnMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_pickDirBtnMouseClicked

    @Action
    public void pickDirectory() {
        /* The "initialDirectory" variable determines what directory is first displayed
         * when choosing a new word list. An empty or a null string will start the chooser
         * in the user's default directory, which for Windows is typically "My Documents",
         * and for *nix is typically the user's home directory.
         */
        String initialDirectory = baseDirTextField.getText();
        if ("".equals(initialDirectory)) {
            initialDirectory = System.getProperty("user.home")+"/media";
        }
        JFileChooser chooser;
        int returnVal;

        chooser = new JFileChooser(initialDirectory);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        returnVal = chooser.showOpenDialog(pickDirBtn);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            /* To create a URL for a file on the local file-system, we simply
             * pre-pend the "file" protocol to the absolute path of the file.
             */
            baseDirTextField.setText(chooser.getSelectedFile().getAbsolutePath());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseDirTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pickDirBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
