/*
 * NewJFrame.java
 *
 * Created on August 6, 2008, 2:27 PM
 */
package chartapp;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author  daniel
 */
public class EnergyDashboard extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public EnergyDashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        chartHolder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ted-Live", "Power-Browser", "Analyze" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setMaximumSize(new java.awt.Dimension(120, 34));
        jList1.setMinimumSize(new java.awt.Dimension(120, 34));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        chartHolder.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(chartHolder);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    if (evt.getValueIsAdjusting()) {
        return;
    }
    String newSel = jList1.getSelectedValue().toString();
    JPanel panel = null;
    if ("Ted-Live".equals(newSel)) {
        panel = new TEDServiceDemo(TEDServiceDemo.OBSERVATION_SLIDING_WINDOW_MS);
        ((TEDServiceDemo)panel).startGenerator();
    } else if ("Power-Browser".equals(newSel)) {
        panel = new DBChartApp();
    } else if ("Analyze".equals(newSel)) {
        panel = new AnalyzeChart();
        ((AnalyzeChart)panel).startTicker();
    } else {
        panel = new JPanel();
    }
    //JButton panel = new JButton("Allo "+new Date());
    chartHolder.removeAll();
    chartHolder.add(panel, BorderLayout.CENTER);
    chartHolder.validate();
}//GEN-LAST:event_jList1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EnergyDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartHolder;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
